
@location = Edmonton, Alberta
@phone = 14157492060
@id = hc0KmC42EzjXbC83eMIDMg
###
GET {{baseUrl}}/businesses/search/phone?phone={{phone}}
Authorization: Bearer {{authorization}}

### 
GET {{baseUrl}}/businesses/search
?term=
&location={{location}}
&latitude=
&longitude=
&radius=
&categories=
&sort_by=rating
&price=1
&open_now=
Authorization: Bearer {{authorization}}